### ISSUE TITLE
SoftAP example not working

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf-provisioning-ios#34] opened 2021-07-01 21:36 UTC
I'd tried the SoftAP example from this repository and received an error saying "Error: Unable to verify device connection" on the app after connecting to the ESP32 in the WiFi settings app. I believe this is a problem with the iOS SoftAP provisioning example because I also tried provisioning with the Android SoftAP provisioning example, and it worked fine. How can I get it to work?

I am using an iPhone 8 running iOS 14.6. I'm also using XCode 12.5. Here are the log outputs I got when receiving the error on the app.

```
2021-07-01 14:25:59.485429-0700 ProvisionTest[715:239905] [connection] nw_endpoint_handler_set_adaptive_read_handler [C2 192.168.4.1:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4)] unregister notification for read_timeout failed
2021-07-01 14:25:59.485565-0700 ProvisionTest[715:239905] [connection] nw_endpoint_handler_set_adaptive_write_handler [C2 192.168.4.1:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4)] unregister notification for write_timeout failed
2021-07-01 14:25:59.514353-0700 ProvisionTest[715:239388] [] nehelper sent invalid result code [1] for Wi-Fi information request
2021-07-01 14:26:26.542252-0700 ProvisionTest[715:239388] [Storyboard] Unknown class _TtC13ProvisionTest8BarTitle in Interface Builder file.
2021-07-01 14:26:26.587114-0700 ProvisionTest[715:239388] [] nehelper sent invalid result code [1] for Wi-Fi information request
2021-07-01 14:27:17.309333-0700 ProvisionTest[715:239388] [Storyboard] Unknown class _TtC13ProvisionTest8BarTitle in Interface Builder file.
2021-07-01 14:27:17.346359-0700 ProvisionTest[715:240286] [connection] nw_endpoint_handler_set_adaptive_read_handler [C4 192.168.4.1:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
2021-07-01 14:27:17.346501-0700 ProvisionTest[715:240286] [connection] nw_endpoint_handler_set_adaptive_write_handler [C4 192.168.4.1:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
2021-07-01 14:27:17.364012-0700 ProvisionTest[715:239388] [] nehelper sent invalid result code [1] for Wi-Fi information request
```

**Comment by vikas-chandra-mnnit** [comment] 2021-07-02 07:24
Hi @tobyloki, we are experiencing this behaviour for some versions of iOS 14. We have an ongoing [thread](https://github.com/espressif/esp-idf-provisioning-ios/issues/33) that relates to your problem. There are a couple of steps mentioned in the [thread](https://github.com/espressif/esp-idf-provisioning-ios/issues/33) that you can try to make this work for your iPhone. Let me know if it solves your problem.

**Comment by tobyloki** [comment] 2021-07-02 09:29
I noticed that a location permission was required, and so I added the appropriate permission to the Info.plist and clicked allow on the app when it gave me a popup. However, the problem still exists.

**Comment by vikas-chandra-mnnit** [comment] 2021-07-02 12:39
> I noticed that a location permission was required, and so I added the appropriate permission to the Info.plist and clicked allow on the app when it gave me a popup. However, the problem still exists.

@tobyloki Please share logs of your ESP32 device to help us better understand the problem. Thanks.

**Comment by tobyloki** [comment] 2021-07-02 21:20
Here are the logs I get after connecting to the ESP32 device.
```
I (26012) wifi:new:<1,0>, old:<1,1>, ap:<1,1>, sta:<0,0>, prof:1
I (26012) wifi:station: b2:f7:7d:a2:61:83 join, AID=1, bgn, 20
I (27162) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.4.2
I (30272) protocomm_httpd: Creating new session: 57
```
Also, here's a screenshot of the error I see on the app.
<img src="https://user-images.githubusercontent.com/35203563/124329483-5b3c4b00-db40-11eb-8516-ccc25fa5093e.png" width="200">

**Comment by vikas-chandra-mnnit** [comment] 2021-07-06 17:33
@tobyloki Unfortunately I was not able to reproduce this issue using the repo sample code. According to the error description, this message appears when the app is not able to fetch the name of the SoftAP with which the iPhone is connected.

This may happen if you have removed the Access WiFi information from project capabilities.
<img width="1123" alt="Screenshot 2021-07-06 at 10 59 28 PM" src="https://user-images.githubusercontent.com/50314592/124642754-d473cf00-dead-11eb-9445-1b99ee4a13bc.png">

Please ensure this capability is present in the sample app. If it is present, let us know so that we can look for some alternate resolutions. Thanks.

**Comment by tobyloki** [comment] 2021-07-06 20:28
Thank you. That seemed to be my problem.

**Comment by shahpiyushv** [comment] 2021-08-12 06:18
Closing this issue since it has been addressed.

**Closed by shahpiyushv** 2021-08-12 06:18 UTC
